export const info = {
  title: "Pagamento",
  namePlaceholder: "Nome*",
  emailPlaceholder: "Email*",
  cpfPlaceholder: "CPF*",
  birthPlaceholder: "Data de nascimento*",
  countryPlaceholder: "País*",
  cepPlaceholder: "CEP*",
  cityPlaceholder: "Cidade*",
  addressPlaceholder: "Endereço*",
  addressNumberPlaceholder: "Número do endereço*",
  dddPlaceholder: "DDD do telefone*",
  telPlaceholder: "Celular*",
  statePlaceholder: "Estado*",
  districtPlaceholder: "Bairro*",
  complementPlaceholder: "Complemento*",
};
