export const AdminGeneralText = {
  title: "Painel do Administrador",
  usersBoxTitle: "Usuários",
  usersPlaceholder: "Pesquise...",
  usersDropdownLabel: "Selecione seu filtro",
  requestsBoxTitle: "Solicitações pendentes",
  requestsPlaceholder: "Pesquise...",
  requestBtn: "VER SOLICITAÇÃO",
};

export const UsersModalText = {
  title: "Usuário",
  nameLabel: "Nome:",
  typeLabel: "Tipo da conta:",
  telLabel: "Telefone:",
  emailLabel: "E-Mail:",
  themesLabel: "Materias:",
  aboutLabel: "Sobre:",
  confirmedLabel: "Confirmação da conta:",
  planLabel: "Plano:",
  banBtn: "BANIR",
  delBtn: "DELETAR",
  banConfirmationTitle: "Deseja banir este usuário?",
  banConfirmationDesc: "A ação não pode ser desfeita.",
  banConfirmationCancelBtn: "CANCELAR",
  banConfirmationConfirmBtn: "BANIR",
  deleteRequestConfirmationTitle: "Deseja deletar essa solicitação?",
  deleteRequestConfirmationDesc: "A ação não pode ser desfeita.",
  deleteRequestConfirmationCancelBtn: "CANCELAR",
  deleteRequestConfirmationConfirmBtn: "DELETAR",
  requestsTitle: "Solicitações vinculadas",
};
