export const MyAccountInfo = {
  changePhotoBtn: "MUDAR FOTO",
  changePasswordTitle: "Senha",
  changePasswordBtn: "MUDAR",
  cancelPasswordBtn: "CANCELAR",
  sendPasswordBtn: "ENVIAR",
  newPasswordPlaceholder: "Nova senha",
  newPasswordConfirmPlaceholder: "Confirmar nova senha",
  personalDataTitle: "Meus Dados",
  personalDataPlaceholders: {
    firstName: "Nome",
    lastName: "Sobrenome",
    birthDate: "Data de nascimento",
    cep: "CEP",
    city: "Cidade",
    address: "Rua",
    addressNumber: "Número da rua",
    ddd: "DDD do telefone",
    cel: "Celular",
    state: "Estado",
    district: "Bairro",
    complement: "Complemento",
  },
  themeTitle: "Matérias e Temas",
  inputPlaceholder: "Pesquise aqui por temas ou matérias",
  themeSelectedTitle: "Selecionados",
  themesAvailableTitle: "Temas",
  aboutTitle: "Sobre você",
  aboutPlaceholder: "Mínimo de 40 palavras",
  themeErrorMessage: "É necessário ter pelo menos 1 tema selecionado",
  submitButton: "SALVAR DADOS",
};
