export const MyAccountInfo = {
  changePhotoBtn: "MUDAR FOTO",
  changePasswordTitle: "Senha",
  changePasswordBtn: "MUDAR",
  personalDataTitle: "Meus Dados",
  personalDataPlaceholders: {
    firstName: "Nome",
    lastName: "Sobrenome",
    birthDate: "Data de nascimento",
    cep: "CEP",
    city: "Cidade",
    address: "Rua",
    addressNumber: "Número da rua",
    ddd: "DDD do telefone",
    cel: "Celular",
    state: "Estado",
    district: "Bairro",
    complement: "Complemento",
  },
  themeTitle: "Matérias e Temas",
  themePlaceholder: "Pesquise a matéria ou o tema aqui...",
  themeSelectedTitle: "Selecionados",
  themesAvailableTitle: "Temas",
  aboutTitle: "Sobre você",
  aboutPlaceholder: "Mínimo de 40 palavras",
  submitButton: "SALVAR DADOS",
};
